version: '3.7'

services:

  api:
    #this tells docker where to look for the Dockerfile to build the image
    build: ./api 
    #name of your container and also the DNS name (nginx will proxy pass to this container from localhost:8000 when using a browser or Postman)
    container_name: api 
    restart: always
    #EXPOSE defines the ports reachable from INSIDE your docker network
    expose: 
      - 8000

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - 80:80

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    #PORTS defines ports reachable from the outside world, like a browser or other clients
    ports: 
      - "8000:8000"
      - "8001:8001"